version: '3.9'

services:
  spring_app:
    container_name: spring_app
    image: spring_mysql
    build: .
    ports:
      - 8080:8080
    environment:
          - DATABASE_URL=jdbc:postgresql://spring_db:5432/test
          - DATABASE_USERNAME=postgres
          - DATABASE_PASSWORD=postgres
    depends_on:
      - spring_db

  spring_db:
    container_name: spring_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test